#! /bin/sh

ARGS=""
for ARG in "$@"; do
	ARGS="$ARGS \"$ARG\""
done

echo "The client is installed in $$CODEPATH$$"
export TPCLIENT_GRAPHICS=$$GRAPHICSPATH$$
export TPCLIENT_DOC=$$DOCPATH$$
echo "Graphics  are installed in $TPCLIENT_GRAPHICS"
echo "Documents are installed in $TPCLIENT_DOC"

cd $$CODEPATH$$
$$CODEPATH$$/tpclient-pywx $ARGS
