# This file has been automatically generated by PyXBoil.
# Please do not edit it manually.

import wx
from wx.xrc import *

class ServerBrowserBase(wx.winMainBase):
	xrc = 'ServerBrowser.xrc'

	def OnInit(self):
		""" This function is called during the class's initialization.
		
		Override it for custom setup (setting additional styles, etc.)"""
		pass

	def __init__(self, parent, res):
		""" Pass an initialized wx.xrc.XmlResource into res """
		
		res = XmlResource(self.xrc)

		# Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
		pre = wx.PrewinMainBase()
		res.LoadOnPanel(pre, parent, "ServerBrowser")
		self.OnInit()
		self.PostCreate(pre)

		# Define variables for the controls
		self.InternetServers = XRCCTRL(self, "InternetServers")
		self.LocalServers = XRCCTRL(self, "LocalServers")
		self.NewAccount = XRCCTRL(self, "NewAccount")
		self.Connect = XRCCTRL(self, "Connect")


